Avoid shading the package org.gradle.internal.classpath to prevent java.lang.NoSuchMethodError
If the test classpath used for test execution with TestKit contains the Tooling API JAR and happens to appear order before the TestKit JAR in the classpath then the following exception would be thrown:

java.lang.NoSuchMethodError: org.gradle.tooling.internal.consumer.DefaultBuildLauncher.withInjectedClassPath(Lorg/gradle/testkit/jarjar/org/gradle/internal/classpath/ClassPath;)Lorg/gradle/tooling/internal/consumer/AbstractLongRunningOperation;

To mitigate do not shade the package so it stays compatible with the original signature of the method added by the Tooling API JAR.

+review REVIEW-5653