don't close previous classloader immediately - classes might be loaded in shutdown of Play application, causes NoClassDefFoundError   when classloader is closed - close previous classloader on the first request after reload
+review REVIEW-5521