Revert "Upgrade to Spock 1.0 everywhere"
This broke IBM JDK 6, again.

java.lang.NoClassDefFoundError:
org.gradle.api.internal.resolve.VariantsMatcherTest$CustomSpecBase$1
    at java.lang.Class.getDeclaredClasses(Class.java:440)
    at java.lang.Class.getDeclaringClass(Class.java:773)
    at java.lang.Class.getEnclosingClass(Class.java:2146)
    at
org.spockframework.gentyref.GenericTypeReflector.isMissingTypeParameters
(GenericTypeReflector.java:75)
    at
org.spockframework.gentyref.GenericTypeReflector.mapTypeParameters(Gener
icTypeReflector.java:54)
    at
org.spockframework.gentyref.GenericTypeReflector.getExactDirectSuperType
s(GenericTypeReflector.java:289)
    at
org.spockframework.gentyref.GenericTypeReflector.getExactSuperType(Gener
icTypeReflector.java:133)
    at
org.spockframework.gentyref.GenericTypeReflector.getExactParameterTypes(
GenericTypeReflector.java:336)
    at
org.spockframework.mock.runtime.StaticMockMethod.getExactParameterTypes(
StaticMockMethod.java:45)
    at
org.spockframework.mock.runtime.StaticMockMethod.getParameterTypes(Stati
cMockMethod.java:41)
    at
org.spockframework.mock.constraint.EqualPropertyNameConstraint.isSatisfi
edBy(EqualPropertyNameConstraint.java:35)
    at
org.spockframework.mock.runtime.MockInteraction.matches(MockInteraction.
java:65)
    at
org.spockframework.mock.runtime.MockInteractionDecorator.matches(MockInt
eractionDecorator.java:42)
    at
org.spockframework.mock.runtime.InteractionScope.match(InteractionScope.
java:63)
    at
org.spockframework.mock.runtime.MockController.handle(MockController.jav
a:36)
    at
org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockIn
terceptor.java:72)
    at
org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invok
e(DynamicProxyMockInterceptorAdapter.java:28)
    at
org.gradle.language.base.internal.model.DefaultVariantsMetaData.extractF
rom(DefaultVariantsMetaData.java:57)
    at org.gradle.api.internal.resolve.VariantsMatcherTest.can use a
custom variant comparator(VariantsMatcherTest.groovy:99)
Caused by: java.lang.ClassNotFoundException:
org.gradle.api.internal.resolve.VariantsMatcherTest$CustomSpecBase$1
    at java.net.URLClassLoader.findClass(URLClassLoader.java:434)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:677)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:643)
    ... 19 more

This reverts commit 84efc925a5eeba0aa8fae56b9b1c769b00686955.