Ignore test when no old JDK is installed
This test was failing for me locally with a cryptic message:
    org.spockframework.runtime.SpockExecutionException: Data provider has no data

Because the 'where' clause in the Spock test provided no values. This change
simply ignores the test in this case.